id: IA5A1F53A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-13T19:49:27+00:00'
last_modified: '2022-06-15T16:43:25.422996+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD95677
  title: སྡེ་དགེའི་བཀའ་བསྟན་དཀར་ཆག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    ADED:
      image_group_id: I1PD95755
      title: Volume 1 of 西藏大藏经总目录 总索引
      total_pages: 858
      order: 1
      base_file: ADED.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
